apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managed-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: managed-csi-premium
